### ISSUE TITLE
Confirm about new students and graduated graduate students

### ISSUE THREAD

**Issue by weikengchen** [nmalkin/secweb#12]
We need to update the website!

Frank Li has graduated. Austin Murdock has graduated. 
Anyone else?

New students include Emma (https://people.eecs.berkeley.edu/~edauterman/). 
Anyone else?

When confirmed, I can also take a look at the courses and push an update.

**Comment by nmalkin** [comment]
[Conor](https://github.com/conorgil), [Eric](https://www.ericswallace.com/), [Vivian](https://www.vivi.sh/)? Also, [Xinyun](https://jungyhuk.github.io/) is missing.

**Comment by nmalkin** [comment]
Updated in #13. Thanks!
